"""Generate .github/ISSUE_TEMPLATE/log-workout.yml from the registry.

The log form's text boxes come pre-loaded with EVERY exercise (grouped
by category, one `Name:` line each). Logging = typing numbers after the
names you trained; untouched `Name:` lines and `# Category` headers are
ignored by the parser. Because the form is generated from the live
registry, custom exercises and dashboard edits show up automatically in
the next workout commit.

Regenerated by regenerate_all(); manual run: python -m irongraph.formgen
"""

from __future__ import annotations

from pathlib import Path

import yaml

from . import paths
from .registry import Registry

# category → (form bucket, display order)
STRENGTH_CATS = ["chest", "back", "shoulders", "biceps", "triceps",
                 "legs", "glutes", "calisthenics", "mobility", "other"]

INTRO = (
    "Every exercise is listed below, ready to log. **Type your numbers after the ones "
    "you did** — e.g. `Barbell Bench Press: 185 lb x 6, 185 x 5` or "
    "`Treadmill: 30 min, speed 3, incline 12`.\n"
    "Leave everything else untouched (blank lines are ignored — no need to delete them). "
    "Sets are comma-separated; `185x6x3` = 3 sets; `// text` adds a note."
)


def _lines(reg: Registry, categories: list[str]) -> str:
    out: list[str] = []
    for cat in categories:
        exs = [e for e in reg.by_id.values() if e.category == cat]
        if not exs:
            continue
        out.append(f"# {cat.capitalize()}")
        out.extend(f"{e.name}:" for e in sorted(exs, key=lambda e: e.name))
        out.append("")
    return "\n".join(out).strip() + "\n"


def build_form(reg: Registry) -> dict:
    def textarea(fid: str, label: str, desc: str, value: str) -> dict:
        return {"type": "textarea", "id": fid,
                "attributes": {"label": label, "description": desc, "value": value},
                "validations": {"required": False}}

    return {
        "name": "🏋️ Log a workout",
        "description": "Every exercise pre-listed — just add numbers next to what you did.",
        "title": "🏋️ Workout Log",
        "labels": ["daily-quest", "log-workout"],
        "assignees": ["ashcodex505"],
        "body": [
            {"type": "markdown", "attributes": {"value": INTRO}},
            textarea("strength", "🏋️ Strength",
                     "weights & reps — numbers only next to what you trained",
                     _lines(reg, STRENGTH_CATS)),
            textarea("cardio", "🏃 Cardio",
                     "duration / distance / speed / incline / level",
                     _lines(reg, ["cardio"])),
            textarea("core", "🧱 Core & bodyweight",
                     "weighted, reps-only, or timed (e.g. Plank: 2m15s)",
                     _lines(reg, ["core"])),
            textarea("notes", "Session notes", "optional — how it felt", ""),
        ],
    }


HEADER = """\
# GENERATED by `python -m irongraph.formgen` from the exercise registry —
# edit data/registry/*.json (or add exercises in the dashboard) instead of
# editing this file; it is rewritten on every workout commit.
# Submitting this form triggers process-workout.yml immediately.
"""


def write_form(reg: Registry | None = None, out: Path | None = None) -> Path:
    reg = reg or Registry.load()
    out = out or paths.repo_root() / ".github" / "ISSUE_TEMPLATE" / "log-workout.yml"
    out.parent.mkdir(parents=True, exist_ok=True)
    class _Dumper(yaml.SafeDumper):
        pass

    def _str(dumper: yaml.SafeDumper, data: str):  # literal blocks for multiline
        style = "|" if "\n" in data else None
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)

    _Dumper.add_representer(str, _str)
    body = yaml.dump(build_form(reg), Dumper=_Dumper, sort_keys=False,
                     allow_unicode=True, width=1000)
    out.write_text(HEADER + body)
    return out


def main() -> None:
    p = write_form()
    print(f"wrote {p}")


if __name__ == "__main__":
    main()
