name: T5 value
description: t5 marker
body:
  - type: textarea
    id: box1
    attributes:
      label: Box one
      description: desc here
      value: |
        # Chest
        Barbell Bench Press:
        Cable Fly:
    validations:
      required: false
